name: build and deploy

on:
  workflow_dispatch:
  push: 
    branches: ['main', 'master']
      
env:
  DOTNET_VERSION: '9.x'
  SOLUTION_PATH: 'TravelPlanner.WebApi'

jobs: 
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - name: Setup .Net
       with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

     - name: Restore dependencies
       run: dotnet restore ${{ env.SOLUTION_PATH }}

     - name: Build
       run: dotnet build ${{ env.SOLUTION_PATH }} --no-restore --configuration Release
