name: build and deploy

on:
  workflow_dispatch:
  push: 
    branches: ['main', 'master']
      
env:
  DOTNET_VERSION: '9.x'
  AZURE_WEBAPI_NAME: travel-app-api
  AZURE_WEBAPI_PACKAGE_PATH: './publish'
  API_PROJECT_PATH: 'WebApi/WebApi.csproj'
  PUBLISH_DIR: './publish'

jobs: 
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v5
     - name: Setup .Net
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: ${{ env.DOTNET_VERSION }}

     - name: Restore dependencies
       run: dotnet restore

     - name: Build
       run: dotnet build --no-restore --configuration Release

     - name: Test
       run: dotnet test --no-build --no-restore --configuration Release --logger trx --results-directory "TestResults-${{ env.DOTNET_VERSION }}"

     - name: Upload test results
       uses: actions/upload-artifact@v4
       with:
         name: dotnet-results-${{ env.DOTNET_VERSION }}
         path: TestResults-${{ env.DOTNET_VERSION }}
       if: ${{ always() }}

     - name: Publish dotnet Api 
       run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore --output ${{ env.PUBLISH_DIR }}

     - name: Upload Publish Artifact
       uses: actions/upload-artifact@v4
       with: 
         name: webapi
         path: ${{ env.AZURE_WEBAPI_PACKAGE_PATH }}

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build-and-test]

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: webapi
          path: ${{ env.AZURE_WEBAPI_PACKAGE_PATH }}
          
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPI_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPI_PACKAGE_PATH }}

