name: build and deploy

on:
  workflow_dispatch:
  push: 
    branches: ['main', 'master']
      
env:
  DOTNET_VERSION: '9.x'

jobs: 
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v5
     - name: Setup .Net
       uses: actions/setup-dotnet@v4
       with:
         dotnet-version: ${{ env.DOTNET_VERSION }}

     - name: Restore dependencies
       run: dotnet restore

     - name: Build
       run: dotnet build --no-restore --configuration Release

     - name: Test
       run: dotnet test --no-build --no-restore --configuration Release --logger trx --result-directory "TestResults-${{ env.DOTNET_VERSION }}"

     - name: Upload test results
       uses: actions/upload-artifect@v4
       with:
         name: dotnet-results-${{ env.DOTNET_VERSION }}
         path: TestResults-${{ env.DOTNET_VERSION }}
       if: ${{ always() }}